name: 'K Thorpe Photography '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.620066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A0D0D0'
    - '#000000'
    - '#909090'
    - '#000000'
    - '#78E8F0'
  brandStrength: 1
  lightness: 0.96875
  saturation: 0.996711
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
